blog_project/urls.py
from django.contrib import admin
from django.urls import path, include   

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls'))
]

blogs/urls.py
"""Define URL patterns for blogs"""

from django.urls import path    # path to map URLs to views
from . import views             # views to process data and render a page

app_name = 'blogs'              # namespace of this app
urlpatterns = [                 # list of urls that can be requested from blogs app
    # Home page
    path('', views.index, name='index'),
    # Page to view all the blogs that have been created
    path('blogs/', views.blogs, name='blogs'),
    # Page to view an individual blog and its posts
    path('blog/<int:blog_id>/', views.blog, name='blog'),
    
    # Page to create new blog
    path('new_blog/', views.new_blog, name='new_blog'),
    # Page to create a new post
    path('new_post/<int:blog_id>/', views.new_post, name='new_post'),
    # Page for editing a post
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
]

blogs/models.py
from django.db import models

# Create your models here: 
# a model tell Django how to work with data
# what will be stored in the app
class Blog(models.Model):
    """A person or organization's blog"""
    date_added = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        """Format the output string for the blog"""
        return self.name
    
class BlogPost(models.Model):
    """Represent a single post in the blog"""
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)    # if a blog gets deleted, all the posts will be too
    
    title = models.CharField(max_length=500)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Format the output string for the post"""
        if len(self.title) < 50:
            return self.title
        return f"{self.title[:50]}..."

blogs/forms.py
from django import forms

from .models import Blog, BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['name']
        labels = {'name': ''}

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title','body']
        labels = {'body':'Text'}
        widgets = {'body': forms.Textarea(attrs={'cols':80})}

        

blogs/views.py
from django.shortcuts import render, redirect
from .models import Blog, BlogPost
from .forms import BlogForm, BlogPostForm

# Create your views here.
def index(request):
    """The homepage for blog"""
    return render(request, 'blogs/index.html')

def blogs(request):
    """Page to view all blogs that have been newly creted"""
    blogs = Blog.objects.order_by('name')
    context = {'blogs': blogs}
    return render(request, 'blogs/blogs.html', context)

def blog(request, blog_id):
    """Page to view a specific blog and its posts"""
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.order_by('-date_added') # reverse lookup <modelname>_set
    context = {'blog': blog, 'posts': posts}
    return render(request, 'blogs/blog.html', context)

def new_blog(request):
    """Page to a new blog. Initial request of a blank form."""
    """Subsequent processing of data submitted in the form."""
    if request.method != 'POST':
        # create a blank form
        form = BlogForm()
    else:
        form = BlogForm(data=request.POST)      # pass the data requested by user through request.POST
        if form.is_valid():         # check all fields have been filled in
            form.save()             # save data to db
            return redirect('blogs:blogs')  # redirect to view of blogs

    # Display a blank or invalid form
    context  = {'form':form}
    return render(request, 'blogs/new_blog.html', context)

def new_post(request, blog_id):
    """Page to create a new post"""
    blog = Blog.objects.get(id=blog_id)

    if request.method != 'POST':
        # No data submitted, hence create a blank entry
        form = BlogPostForm()
    else:
        form = BlogPostForm(data=request.POST)      # pass the data requested by user through request.POST
        if form.is_valid():
            new_post = form.save(commit = False)   # do not save yet to db
            new_post.blog = blog
            new_post.save()
            return redirect('blogs:blog', blog_id=blog_id)  # redirect to the specifc blog_id with all its entries
    
    # Display a blank form or invalid form in case info is missing
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/new_post.html', context)

def edit_post(request, post_id):
    """Edit an existing post"""
    post = BlogPost.objects.get(id=post_id)
    blog  = post.blog

    if request.method != 'POST':
        # Initial request: show the pre-fill post
        form = BlogPostForm(instance=post)  # create an instance of BlogPostForm with data of the pre-existing 'post'
    else:
        # POST changed data submitted with request.POST, then process data
        form = BlogPostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:blog', blog_id = blog.id)
    
    context = {'post': post, 'blog': blog, 'form': form}
    return render(request, 'blogs/edit_post.html', context)

blogs/templates/blogs/base.html
<p>
  <a href="{% url 'blogs:index' %}">Blog Host</a>
  <a href="{% url 'blogs:blogs' %}">All blogs</a>
</p>

{% block content %}{% endblock content%}

blogs/templates/blogs/blog.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p>Blog: {{blog.name}}</p>
  <p>Entries:</p>  
  <p>
    <a href="{% url 'blogs:new_post' blog.id %}">Add a new entry</a>
  <p>  
  <ul>
    {% for post in posts %}
      <li>
        <p>{{ post.date_added|date:'M d, Y H:i' }}</p>
        <p>{{ post.title }}</p>
        <p>{{ post.body|linebreaks }}</p>    {% comment %} long text entries include linebreaks, instead of long uninterrupted text. {% endcomment %}
        <p>
          <a href="{% url 'blogs:edit_post' post.id %}">Edit post</a>
        </p>  
      </li>
    {% empty %}
      <li>This blog does not have any posts yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p>All Blogs</p>
  <ul>
    {% for blog in blogs %}
      <li>
          <a href="{% url 'blogs:blog' blog.id %}">{{blog.name}}</a>
      </li>
    {% empty %}
      <li>No topics have been added.</li>  
    {% endfor %}
  </ul>
  
  <a href="{% url 'blogs:new_blog' %}">Add a new blog</a>

{% endblock content %}

blogs/templates/blogs/edit_post.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p>
    <a href="{% url 'blogs:blogs' %}">All blogs</a> 
    /
    <a href="{% url 'blogs:blog' blog.id %}">{{ blog.name }}</a>
    /
    <a href="{% url 'blogs:edit_post' post.id %}">{{ post.title }}</a>
  </p>

  <p>Edit entry:</p>
  <form action="{% url 'blogs:edit_post' post.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name='submit'>Save changes</button>
    <a href="{% url 'blogs:blog' blog.id %}">
      <button type="button">Cancel</button>
    </a>
  </form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p>Blog allows to create the blog, and share it with other people.</p>
{% endblock content %}

blogs/templates/blogs/new_blog.html
{% extends 'blogs/base.html' %}

{% block content %}

<p>
  <a href="{% url 'blogs:blogs' %}">List of blogs.</a>
</p>

<p>Add a new blog:</p>

<form action="{% url 'blogs:new_blog' %}" method='post'> {% comment %} 1st argument of action tells where to send data: to the function new_blog() in views {% endcomment %}
  {% csrf_token %}
  {{ form.as_div }}
  <button name='submit'>Add topic</button>
</form>

{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends 'blogs/base.html' %}

{% block content %}
  <p> 
    <a href="{% url 'blogs:blog' blog.id %}">{{blog.name}}</a>
  </p>  
  <form action="{% url 'blogs:new_post' blog.id %}" method='post'> {% comment %} 1st argument of action tells where to send data: to the function new_post() in views. 2nd argument associate new post to the correct blog {% endcomment %}
    {% csrf_token %}    {% comment %} prevent unauthorized access to server, cross-site request forgery {% endcomment %}
    {{ form.as_div }}
    <button name="submit">Add post</button>
  </form>

{% endblock content %}